### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by jasonkarns** [jacobwgillespie/git-sync#12]
I've been a hub user for over a decade and still install `hub` _solely_ for the `sync` subcommand.

I'm very excited to try git-sync so I can slim down to just `git-sync` and `gh`.

However, considering how dangerous operations with git can be (and the sensitive nature of client code), I'd be remiss if I didn't review how git-sync works before letting it run wild in my repos.

Would you by any chance be willing to document (in README or elsewere) exactly what git-sync does under the covers? What git operations does it perform and what github api calls does it make? And does it work for private repos or only OSS/public repos?

I'll attempt to derive these things myself by reading the source, but I don't know Go. An overview of the underlying git/gh commands from the author(s) would help immensely.

And thank you again for sharing the tool!

**Comment by jacobwgillespie** [comment]
Hey! Yeah same, I made this so I could transition from `hub` -> `gh`.

I don't have a list of commands separate from the source, but I think you may be able to follow the source with a bit of extra context:

1. This project uses 0 external dependencies (this file is empty: https://github.com/jacobwgillespie/git-sync/blob/main/go.mod), specifically to avoid any chance of them doing nefarious things with git repos
2. This file contains functions that execute the `git` CLI: https://github.com/jacobwgillespie/git-sync/blob/main/git/git.go
3. The code only executes `git`, there's no dependency on `gh`

Taking a look at `git.go`, those functions essentially wrap the `git` CLI and return the output, for example:

* `SymbolicRef(REF)` - executes `git symbolic-ref REF` and returns the first line: https://github.com/jacobwgillespie/git-sync/blob/main/git/git.go#L204-L210
* `LocalBranches()` - executes `git branch --list` and returns the lines as an array: https://github.com/jacobwgillespie/git-sync/blob/main/git/git.go#L110-L120
* `Remotes()` - executes `git remote -v`, parses the output with a regex to extract the remote names, returns the sorted list: https://github.com/jacobwgillespie/git-sync/blob/main/git/git.go#L142-L180

Then [`main.go`](https://github.com/jacobwgillespie/git-sync/blob/main/main.go) has the actual logic, to find all the local branches and compare them against their remote status, to update them if necessary or clean them up if they've been merged.

IIRC, all the logic in `main.go` was copied from `hub`'s implementation, with some cleanup, plus I added the ability for it to detect and clean up squash-merged branches, which I don't think `hub` had implemented at the time: https://github.com/jacobwgillespie/git-sync/commit/be0e43c5cbcf33b788ad9a2f1b02c4a810451a8b#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261.

**Comment by jacobwgillespie** [comment]
Here's the equivalent file from `hub` if you're curious: https://github.com/mislav/hub/blob/master/commands/sync.go.

**Comment by jasonkarns** [comment]
Thanks for the walkthrough
